# see https://cert-manager.io/docs/configuration/selfsigned/#bootstrapping-ca-issuers

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-issuer
spec:
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  commonName: "*.localho.st Kube / KIND TLS Issuer"
  subject:
    organizations:
      - "International Business Machines Incorporated"
  secretName: ca-issuer-secret
  issuerRef:
    name: root-tls-cert-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-issuer-secret



